modLoader = "javafml"
loaderVersion = "[37,)"
license = "GNU LGPLv3"
issueTrackerURL = "https://github.com/MORIMORI0317/GameMenuRemoveGFARB/issues"
[[mods]]
modId = "gamemenuremovegfarb"
version = "${file.jarVersion}"
displayName = "Game Menu Remove GFARB"
logoFile = "logo.png"
authors = "MORIMORI0317"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/game-menu-remove-gfarb"
description = "Thank you for downloading!\nThis mod is a mod that removes the \"Give Feedback\" and \"Report Bugs\" buttons in the game menu.\nThe Ikisugi MOD..."

[modproperties.gamemenuremovegfarb]
catalogueImageIcon = "logo.png"